### ISSUE TITLE
"flutter packages get" issue

### ISSUE THREAD

**Issue by kostaa** [davidmarne/built_redux_rx#1]
"flutter packages get" fails with the following error:

Package build_runner has no versions that match >=0.4.0 <0.5.0 derived from:
- built_redux_rx depends on version ^0.4.0

**Comment by davidmarne** [comment]
Yea the dependency on built value was not allowing the 5.x.x line.
I just opened the built_value range up and update the rx dependency [here](https://github.com/davidmarne/built_redux_rx/pull/2) and published a new version to pub.

Hopefully you'll have better luck now.

**Comment by kostaa** [comment]
Thanks for that all is good now.
